application: torah-squash
version: 5_3
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /css
  static_dir: css
- url: /javascript
  static_dir: javascript
- url: /src
  static_dir: src
- url: /images/login_page
  static_dir: images/login_page
  mime_type: image/login_page/png
- url: /images/toys
  static_dir: images/toys
  mime_type: image/toys/png
- url: /images
  static_dir: images
  mime_type: image/png
- url: /images/compliments
  static_dir: images/compliments
  mime_type: image/compliments/png
- url: /photoshoped
  static_dir: photoshoped
  mime_type: photoshoped/png
- url: /music
  static_dir: music
  mime_type: music/mp3

- url: /game/.*
  script: game.app
- url: /online/.*
  script: online.app
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
